[tool.ruff]
line-length = 88

[project]
name = "assist-traces"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = [
  "pydantic>=2.7",
]

[project.optional-dependencies]
test = [
  "homeassistant==2024.6.0",
  "pytest-asyncio",
]
